apiVersion: v1
kind: Service
metadata:
  name: internsaathi-backend
  namespace: internsaathi
  labels:

    app.kubernetes.io/instance: internsaathi
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: internsaathi-backend
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/part-of: internsaathi
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: internsaathi-service
      targetPort: 3000
  selector:

    app.kubernetes.io/name: internsaathi-backend
