apiVersion: apps/v1
kind: Deployment
metadata:
  name: internsaathi-frontend
  namespace: internsaathi
  labels:

    app.kubernetes.io/instance: internsaathi
    app.kubernetes.io/component: frontend
    app.kubernetes.io/name: internsaathi-frontend
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/part-of: internsaathi
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:

      app.kubernetes.io/name: internsaathi-frontend
  template:
    metadata:
      labels:

        app.kubernetes.io/instance: internsaathi
        app.kubernetes.io/component: frontend
        app.kubernetes.io/name: internsaathi-frontend
    spec:
      serviceAccountName: internsaathi
      containers:
        - name: internsaathi-frontend
          image: 'hdxt25/internsaathi-frontend:v1'
          imagePullPolicy: IfNotPresent
          ports:

            - containerPort: 80
              name: service
          env:
            - name: VITE_API_URL
              value: 'http://localhost:3000'
          resources:
            limits:
              memory: 50Mi
          volumeMounts:
      volumes:
