apiVersion: v1
kind: Service
metadata:
  name: internsaathi-frontend
  namespace: internsaathi
  labels:
    
    app.kubernetes.io/instance: internsaathi
    app.kubernetes.io/component: frontend
    app.kubernetes.io/name: internsaathi-frontend
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/part-of: internsaathi
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: internsaathi-service
      targetPort: 80
  selector:
    
    app.kubernetes.io/name: internsaathi-frontend
